name: Lint

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew
      - name: Ktlint
        run: ./gradlew ktlintCheck