name: Main

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  JAVA_VERSION: 17

jobs:
  get-tag:
    uses: ./.github/workflows/get-tag.yml

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      java-version: ${{ env.JAVA_VERSION }}

  build:
    uses: ./.github/workflows/build.yml
    needs: [get-tag, lint]
    with:
      java-version: ${{ env.JAVA_VERSION }}
      tag-name: ${{ needs.get-tag.outputs.tag-name }}

  release:
    uses: ./.github/workflows/release.yml
    needs: [get-tag, build]
    with:
      java-version: ${{ env.JAVA_VERSION }}
      tag-name: ${{ needs.get-tag.outputs.tag-name }}
      is-prerelease: ${{ github.ref != 'refs/heads/main' }}