name: Main

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      java-version: 17

  build:
    uses: ./.github/workflows/build.yml
    needs: [get-version, lint]
    with:
      java-version: 17
      product-version: ${{ needs.get-version.outputs.version }}

  release:
    uses: ./.github/workflows/release.yml
    needs: [get-version, build]
    with:
      java-version: 17
      product-version: ${{ needs.get-version.outputs.version }}
      is-prerelease: ${{ github.ref != 'refs/heads/main' }}