name: Lint and Build

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      java-version: '17'

  build:
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      java-version: '17'
