name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Extract tag name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build -Pversion=$TAG_NAME

      #- name: Rename JAR file
      #  run: |
      #    ls
      #    JAR_PATH=./build/distributions/Kulibin.jar
      #    NEW_JAR_PATH=./build/distributions/Kulibin-$TAG_NAME.jar
      #    mv $JAR_PATH $NEW_JAR_PATH
      #    echo "JAR file renamed to $NEW_JAR_PATH"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/Kulibin-$TAG_NAME.jar
          asset_name: Kulibin-$TAG_NAME.jar
          asset_content_type: application/java-archive